### ISSUE TITLE
Continue Xiao's first insight

### ISSUE THREAD

**Issue by yxliang01** [yxliang01/Mining-Behaviour-Analysis#1]
This reward reduction happened in Litecoin as well on Aug-25-2015. 

The hash rate wasn't affected by this event. 
![image](https://cloud.githubusercontent.com/assets/9780746/23597488/3a199de6-0201-11e7-9c20-38cd0ed57711.png)
From coinwarz.com

However, the price of Litecoin might have dropped because of this.

![image](https://cloud.githubusercontent.com/assets/9780746/23597599/4866c31e-0202-11e7-8663-c51103f88a84.png)
From https://bitcoinwisdom.com/markets/okcoin/ltccny

**Comment by yxliang01** [comment]
More analytics have to be done in order make sure there's no other events happening at the same time.

**Comment by Eleutherado** [comment]
Here is the pdf of what u sent me, just for completion. 
[Mid-term-Presentation-Xiao.pdf](https://github.com/yxliang01/Mining-Behaviour-Analysis/files/820220/Mid-term-Presentation-Xiao.pdf)
