### ISSUE TITLE
Hypotheses 

### ISSUE THREAD

**Issue by Eleutherado** [yxliang01/Mining-Behaviour-Analysis#3]
1. Is there a true difference in **mining power** distribution between anonymous and named users? Do anons have more power?
2. Is there a true difference in **hobbyist vs professional** distribution between anonymous and named users? Is there an equal mix of H vs P in anon vs named?
   - How many miners can we classify as "professional" vs hobbyists?

**Comment by yxliang01** [comment]
For Q1
======
Sum(all shares of anonymous) = 286358978362607.0
Sum(all shares of named users) = 191030170917713.0

**Comment by yxliang01** [comment]
For Q2
=====

I have written script. Please see 73c98331bfb3025daa2df3354263b48a9a0287e6
